services:
  - type: web
    name: django-university-app
    runtime: docker
    dockerfilePath: ./tp3/dockerfile
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        fromDatabase:
          name: spring_vlc9
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: tp3.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: PYTHONUNBUFFERED
        value: 1

databases:
  - name: spring_vlc9
    databaseName: spring_vlc9
    user: spring_vlc9_user
    region: oregon
    plan: free