services:
  - type: web
    name: django-university-app
    runtime: docker
    dockerfilePath: ./tp3/dockerfile
    dockerContext: ./tp3
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        value: postgresql://spring_vlc9_user:293WYiOJjjKvAKFbTxmnt8GzlYORJTfR@dpg-d4j32gvpm1nc73dot76g-a.oregon-postgres.render.com:5432/spring_vlc9
      - key: DJANGO_SETTINGS_MODULE
        value: tp3.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com,django-university-app.onrender.com
      - key: PYTHONUNBUFFERED
        value: 1
      - key: LOG_LEVEL
        value: INFO
        
databases:
  - name: spring_vlc9
    databaseName: spring_vlc9
    user: spring_vlc9_user
    region: oregon
    plan: free